### PR TITLE
Add tag <a> in listItem template

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
@mairatma I have a question. I can change the components style?

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
@clovisdasilvaneto not sure if this is what you asked, but you can pass classes to any component via the `elementClasses` param. For example, if you want to add a class to a call to metal-list you can do in soy:

```
{call List.render}
  {param elementClasses: 'my-class' /}
{/call}
```

**Comment by clovisdasilvaneto** [comment]
I understood, but I was referring to stylize the metal components that are created. for example, I would like to stylize the metal-list component and send you a pull request

**Comment by fernandosouza** [comment]
@mairatma, @clovisdasilvaneto, don't you think, guys that it will be nice a test case for this PR just in case to prevent regressions?

**Comment by mairatma** [comment]
Ahh got it now. We actually usually prefer leaving the component as simple as possible regarding style so that it can be stylized anyway the developer wants later. We just use bootstrap as much as possible, avoiding custom css. That said I agree that when metal-list is used with avatars on its own it's just too ugly, forcing people to have to add some more css. Maybe we could improve that use case a little, so if you want to give a try it'd be great, just remember to try to not add too much, as we don't want to force too much styling that the developers may want to override later on their sites.

**Comment by mairatma** [comment]
@fernandosouza oh you're right. This feature is only present in the soy file, but it's an important feature anyway, so it's important to add a test case for it. @clovisdasilvaneto could you add a simple test case using this new feature you've added? :)

**Comment by fernandosouza** [comment]
@mairatma, I think @clovisdasilvaneto can do a great job only adding more Bootstrap CSS classes. :)

**Comment by fernandosouza** [comment]
@mairatma, @clovisdasilvaneto, I'm not sure, but I've heard somewhere that Spain team is kinda merging Lexicon's style guide with Metal components. That mans that they are developing new components following Lexicon. If I'm right probably they already have stylized better this component.

Maybe I'm wrong, but maybe it's better we confirm this.

**Comment by mairatma** [comment]
Yeah, they probably did. The WeDeploy team has also stylized this on their side. So if we do change some of the styling for metal-list it's important that we know what they've done so that we can avoid causing problems for both of them with these changes.

**Comment by fernandosouza** [comment]
Yeah, @mairatma. If there is a repo for this we could help them. I've asked @brunobasto about it. let's see what he says.

**Comment by mairatma** [comment]
There's https://github.com/liferay-lexicon/ and https://github.com/wedeploy/westyle. Not sure if they're public, but Bruno may help get permission :)

**Comment by clovisdasilvaneto** [comment]
show guys, so I will take a set in the list of style, leaving flexile developer adjust.

**Pull request merged**
